version: '3.7'
services:
  frontend:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - '3000:80'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
      - ./build/index.html:/var/www/html/index.html
    depends_on:
      - frontend